### ISSUE TITLE
Upgrade to `moz-fx-data-shared-prod.telemetry_stable.main_v5`

### ISSUE THREAD

**Issue by saschanaz** [mozilla/firefox-public-data-report-etl#21]
https://github.com/mozilla/firefox-public-data-report-etl/blob/0b16b3222de0216fa71536e6740576ef0c4f35b2/public_data_report/hardware_report/hardware_report.py#L34

main_v4 doesn't seem to work anymore, doing so throws permission error.

**Comment by akkomar** [comment]
Fixed in https://github.com/mozilla/firefox-public-data-report-etl/pull/22
